
[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
ignore_missing_imports = true
python_version = 3.11
warn_return_any = true
warn_unused_configs = true

[tool.black]
line-length = 120
